// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using SubVora.Domain.Enums;
using SubVora.Infrastructure.Data;

#nullable disable

namespace SubVora.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711185132_AddNotificationsLog")]
    partial class AddNotificationsLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing_cycle_type", new[] { "monthly", "one_time", "weekly", "yearly" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_source_type", new[] { "bank_account", "card", "other", "wallet" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubVora.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_user_id_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("SubVora.Domain.Entities.FxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("rate");

                    b.Property<string>("TargetCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("target_currency");

                    b.HasKey("Id")
                        .HasName("pk_fx_rates");

                    b.HasIndex("BaseCurrency", "TargetCurrency")
                        .IsUnique()
                        .HasDatabaseName("ix_fx_rates_base_currency_target_currency");

                    b.ToTable("fx_rates", (string)null);
                });

            modelBuilder.Entity("SubVora.Domain.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AlertDaysAdvance")
                        .HasColumnType("integer")
                        .HasColumnName("alert_days_advance");

                    b.Property<DateTimeOffset>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications_log");

                    b.HasIndex("UserSubscriptionId", "AlertDaysAdvance", "SentAt")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_log_user_subscription_id_alert_days_advance_s");

                    b.ToTable("notifications_log", (string)null);
                });

            modelBuilder.Entity("SubVora.Domain.Entities.PaymentSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<PaymentSourceType>("SourceType")
                        .HasColumnType("payment_source_type")
                        .HasColumnName("source_type")
                        .HasDefaultValueSql("'other'::payment_source_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_sources");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payment_sources_user_id");

                    b.ToTable("payment_sources", (string)null);
                });

            modelBuilder.Entity("SubVora.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SubVora.Domain.Entities.SubscriptionCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("logo_url");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<Vector>("SemanticEmbedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("semantic_embedding");

                    b.HasKey("Id")
                        .HasName("pk_subscription_catalog");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_subscription_catalog_category_id");

                    b.HasIndex("ProviderName")
                        .IsUnique()
                        .HasDatabaseName("ix_subscription_catalog_provider_name");

                    b.ToTable("subscription_catalog", (string)null);
                });

            modelBuilder.Entity("SubVora.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("preferred_currency");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SubVora.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AlertDaysAdvance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("alert_days_advance");

                    b.Property<Guid?>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<decimal>("CostAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cost_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("custom_name");

                    b.Property<BillingCycleType>("CycleCadence")
                        .HasColumnType("billing_cycle_type")
                        .HasColumnName("cycle_cadence")
                        .HasDefaultValueSql("'monthly'::billing_cycle_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFreeTrial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_free_trial");

                    b.Property<DateOnly>("NextBillingDate")
                        .HasColumnType("date")
                        .HasColumnName("next_billing_date");

                    b.Property<Guid?>("PaymentSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_source_id");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_subscriptions");

                    b.HasIndex("CatalogId")
                        .HasDatabaseName("ix_user_subscriptions_catalog_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_user_subscriptions_category_id");

                    b.HasIndex("NextBillingDate")
                        .HasDatabaseName("idx_subs_next_billing")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("PaymentSourceId")
                        .HasDatabaseName("ix_user_subscriptions_payment_source_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_subs_user_id");

                    b.ToTable("user_subscriptions", (string)null);
                });

            modelBuilder.Entity("SubVora.Domain.Entities.Category", b =>
                {
                    b.HasOne("SubVora.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_categories_users_user_id");
                });

            modelBuilder.Entity("SubVora.Domain.Entities.NotificationLog", b =>
                {
                    b.HasOne("SubVora.Domain.Entities.UserSubscription", null)
                        .WithMany()
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_log_user_subscriptions_user_subscription_id");
                });

            modelBuilder.Entity("SubVora.Domain.Entities.PaymentSource", b =>
                {
                    b.HasOne("SubVora.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_sources_users_user_id");
                });

            modelBuilder.Entity("SubVora.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SubVora.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("SubVora.Domain.Entities.SubscriptionCatalogItem", b =>
                {
                    b.HasOne("SubVora.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_subscription_catalog_categories_category_id");
                });

            modelBuilder.Entity("SubVora.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("SubVora.Domain.Entities.SubscriptionCatalogItem", null)
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_subscriptions_subscription_catalog_catalog_id");

                    b.HasOne("SubVora.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_subscriptions_categories_category_id");

                    b.HasOne("SubVora.Domain.Entities.PaymentSource", null)
                        .WithMany()
                        .HasForeignKey("PaymentSourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_subscriptions_payment_sources_payment_source_id");

                    b.HasOne("SubVora.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscriptions_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
